# default-dmeo is a no sense image for aviod warning , real image is ${DOCKER_BASE_IMAGE} from docker-compose.yaml
ARG DOCKER_BASE_IMAGE=default-dmeo 
FROM ${DOCKER_BASE_IMAGE}

WORKDIR /workspace
ARG PROJECT_PATH
ARG PROJECT_NAME
ARG DOCKER_NAME

COPY ${PROJECT_PATH}/requirements.txt ./


RUN --mount=type=cache,sharing=locked \
  set -e && \
  pip install -r requirements.txt --index-url https://pypi.tuna.tsinghua.edu.cn/simple




