FROM comfyui-base:latest

WORKDIR /workspace
# ARG PROJECT_ROOT=.

# # # Copy the files from this project's server directory into the container's current working directory.
# COPY ${PROJECT_ROOT} .

EXPOSE 8188 
CMD  bash -c 'python main.py --listen 0.0.0.0 --disable-auto-launch --highvram --disable-metadata'
